# Base configuration used across all environments
baseURL = "https://loudlyproud.netlify.app"
title = 'Loudly Proud'
contentDir = "content"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true  # Forces all languages into their own directory
ignoreFiles = ['content/books/temp/.*']
i18nDir = "i18n"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
  [languages.ru]
    languageName = "Русский"
    weight = 2
    contentDir = "content/ru"
  [languages.fa]
    languageName = "فارسی"
    weight = 3
    contentDir = "content/fa"
  [languages.ku]
    languageName = "کوردی"
    weight = 4
    contentDir = "content/ku"

[build]
  writeStats = true

[markup]
[markup.postCSS]
enable = true
config = "postcss.config.js"

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = false  # Disable raw HTML for security
hardWraps = true  # Convert line breaks to <br>
xhtml = true  # Use XHTML-style tags
[markup.goldmark.parser]
autoHeadingAnchor = true
wrapStandAloneImageWithinParagraph = true
attribute = true  # Enable HTML attributes in markdown
[markup.goldmark.extensions]
table = true
strikethrough = true
linkify = true
taskList = true
typographer = true
footnote = true  # Enable footnotes
definitionList = true  # Enable definition lists
[markup.highlight]
style = "monokai"  # Syntax highlighting style
lineNos = true  # Show line numbers
lineNumbersInTable = true  # Better line number formatting
noClasses = false  # Use CSS classes for styling
guessSyntax = true  # Auto-detect language if not specified

[taxonomies]
  tag = "tags"

[section]
[section.books]
title = "Books"
type = "books"

[section.feedback]
title = "Feedback"
type = "feedback"

[permalinks]
books = "/books/:slugorcontentbasename/"
feedback = "/feedback/"
# Define how taxonomy term URLs should be structured
tags = "/tags/:slug/"

# Configure how Hugo generates taxonomy URLs
[outputs]
  taxonomy = ["HTML"]
  term = ["HTML"]
  home = ["HTML"]

[params]
  description = "A multilingual catalog of LGBTQIA+ literature featuring curated books, comprehensive tagging, and community contributions. Browse, search, and discover queer literature in multiple languages."

[params.features]
  search = true
  multilingual = true
