# Base configuration used across all environments
baseURL = "/"
title = 'Loudly Proud'
contentDir = "content"
defaultContentLanguage = "ru"
defaultContentLanguageInSubdir = true
ignoreFiles = ['content/books/temp/.*']
i18nDir = "i18n"

[build]
  writeStats = true

[markup]
[markup.postCSS]
enable = true
config = "postcss.config.js"

[taxonomies]
  tag = "tags"

[section]
[section.books]
title = "Books"
type = "books"

[permalinks]
books = "/books/:slugorfilename/"
# Define how taxonomy term URLs should be structured
tags = "/tags/:slug/"

# Configure how Hugo generates taxonomy URLs
[outputs]
  taxonomy = ["HTML"]
  term = ["HTML"]

[params]
  description = "A bilingual catalog of LGBTQIA+ literature featuring curated books, comprehensive tagging, and community contributions. Browse, search, and discover queer literature in Russian and English."
  darkMode = true
  images = ["/images/og-default.jpg"]  # Default social sharing image

[params.features]
  search = true
  multilingual = true
