baseURL = "/"
languageCode = 'en-us'
title = 'Loudly Proud'

[params]
heroTitle = "Литературный каталог Loudly Proud"
heroDescription = "Друзья, это наша общая библиотека квир-литературы. Знаете книгу, которой здесь не хватает? Заметили неточность? <a href='https://forms.gle/YHhojq3Ts2LsDF6G8'>Дайте мне знать</a> – вместе мы сделаем этот каталог лучше."
heroFeedbackLink = "https://forms.gle/YHhojq3Ts2LsDF6G8"
heroTelegram = "<a href='https://t.me/loudlyProud'>Телеграм канал для анонсов о сайте</a>"

[build]
writeStats = true

[outputs]
home = ["HTML"]
section = ["HTML"]

[markup]
[markup.postCSS]
enable = true
config = "postcss.config.js"

[permalinks]
books = "/books/:section/:slug/"
[languages]
[languages.en]
languageName = "English"
weight = 2
[languages.ru]
languageName = "Русский"
weight = 1
