baseURL = "/"
title = 'Loudly Proud'
contentDir = "content"
defaultContentLanguage = "ru"
defaultContentLanguageInSubdir = true
ignoreFiles = ['content/books/temp/.*']
i18nDir = "i18n"

[params]
heroTitle = "Литературный каталог Loudly Proud"
heroDescription = "Друзья, это наша общая библиотека квир-литературы. Знаете книгу, которой здесь не хватает? Заметили неточность? <a href='https://forms.gle/YHhojq3Ts2LsDF6G8' class=styled-link>Дайте мне знать</a> – вместе мы сделаем этот каталог лучше."
heroFeedbackLink = "https://forms.gle/YHhojq3Ts2LsDF6G8"
heroTelegram = "<a href='https://t.me/loudlyProud' class=styled-link>Телеграм канал для анонсов о сайте</a>"

[taxonomies]
  tag = "tags"

[build]
  writeStats = true

[markup]
[markup.postCSS]
enable = true
config = "postcss.config.js"


[section]
[section.books]
title = "Books"
type = "books"


[permalinks]
books = "/books/:slugorfilename/"

[languages]
[languages.en]
languageName = "English"
weight = 2
languageCode = "en"
contentDir = "content/en"
disabled = false
[languages.ru]
languageName = "Русский"
weight = 1
languageCode = "ru"
contentDir = "content/ru"
disabled = false
