[build]
publish = "public"
command = "npm install && npm run build && hugo --gc --minify"

[build.environment]
NODE_VERSION = "20"
HUGO_VERSION = "0.134.3"  # Set Hugo version globally

# Production context
[context.production.environment]
HUGO_ENV = "production"
HUGO_BASEURL = "https://loudlyproud.netlify.app/"

# Preview context (for pull requests)
[context.deploy-preview.environment]
HUGO_ENV = "preview"
HUGO_BASEURL = "/"  # This will be automatically set by Netlify

# Branch deploys (other than production)
[context.branch-deploy.environment]
HUGO_ENV = "staging"
HUGO_BASEURL = "/"  # This will be automatically set by Netlify

# Specific branch context (optional)
[context.preview.environment]  # 'preview' here is your branch name
HUGO_ENV = "preview"
HUGO_BASEURL = "/"