[build]
publish = "public"
command = "npm install && npm run build && git submodule update --init --recursive && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.134.3-extended"
HUGO_BASEURL = "https://loudlyproud.netlify.app/"
HUGO_ENV = "production"
HUGO_EXTENDED = "true"
