# static/admin/config.yml
local_backend: true

backend:
  name: git-gateway
  branch: preview

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "books"
    label: "Books"
    folder: "content/ru/books"
    create: true
    fields:
      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          default: false,
          required: true,
        }
      - { label: "Title", name: "title", widget: "string", required: true }
      - {
          label: "Slug",
          name: "slug",
          widget: "slug-generator",
          required: true,
        }
      - { label: "Type", name: "type", widget: "hidden", default: "books" }
      - label: "Params"
        name: "params"
        widget: "object"
        required: true
        fields:
          - {
              label: "Book Title",
              name: "book_title",
              widget: "book-title",
              required: true,
            }
          - {
              label: "Authors",
              name: "authors",
              widget: "list",
              field: { label: "Author", name: "author", widget: "string" },
              required: true,
              allow_add: true,
              collapsed: false,
              hint: "Add each author separately, including translations if available",
            }
          - {
              label: "Book Description",
              name: "book_description",
              widget: "markdown",
              required: false,
              hint: "Full description of the book, can include multiple paragraphs",
            }
          - {
              label: "Short Book Description",
              name: "short_book_description",
              widget: "text",
              required: false,
              hint: "Brief summary of the book",
            }
          - {
              label: "Cover",
              name: "cover",
              widget: "string",
              pattern: ['^https?:\/\/.*', "Must be a valid URL"],
              required: false,
            }
          - {
              label: "Cover Alt Text",
              name: "cover_alt",
              widget: "string",
              required: false,
              hint: "Alternative text description for the cover image(s)",
            }
          - {
              label: "ISBN",
              name: "isbn",
              widget: "string",
              required: false,
              hint: "ISBN-10 or ISBN-13, can include hyphens",
            }
          - {
              label: "Additional ISBNs",
              name: "additional_isbns",
              widget: "list",
              field: { label: "ISBN", name: "isbn", widget: "string" },
              required: false,
              allow_add: true,
              collapsed: false,
              hint: "Additional ISBNs for other editions",
            }
          - {
              label: "Languages",
              name: "languages",
              widget: "list",
              field: { label: "Language", name: "language", widget: "string" },
              required: false,
              allow_add: true,
              collapsed: false,
            }
          - {
              label: "Page Count",
              name: "page_count",
              widget: "string",
              required: false,
              hint: "Can use approximate format like '~300'",
            }
          - {
              label: "Publication Year",
              name: "publication_year",
              widget: "string",
              required: false,
              hint: "Can use approximate dates",
            }
          - {
              label: "Goodreads Link",
              name: "goodreads_link",
              widget: "string",
              pattern: ['^https?:\/\/.*', "Must be a valid URL"],
              required: false,
            }
          - {
              label: "Series",
              name: "series",
              widget: "string",
              required: false,
            }
          - {
              label: "Translators",
              name: "translators",
              widget: "list",
              field:
                { label: "Translator", name: "translator", widget: "string" },
              required: false,
              allow_add: true,
              collapsed: false,
            }
          - {
              label: "Publishers",
              name: "publishers",
              widget: "list",
              field:
                { label: "Publisher", name: "publisher", widget: "string" },
              required: false,
              allow_add: true,
              collapsed: false,
            }
          - {
              label: "Russian Translation Status",
              name: "russian_translation_status",
              widget: "select",
              options:
                [
                  { label: "Unknown", value: "unknown" },
                  { label: "Might Exist", value: "might_exist" },
                  { label: "Unlikely to Exist", value: "unlikely_to_exist" },
                  { label: "Does Not Exist", value: "does_not_exist" },
                  { label: "Exists", value: "exists" },
                ],
              required: false,
            }
          - {
              label: "Russian Audioversion",
              name: "russian_audioversion",
              widget: "boolean",
              required: false,
              default: false,
            }
          - {
              label: "Tags",
              name: "tags",
              widget: "list",
              field: { label: "Tag", name: "tag", widget: "string" },
              required: false,
              allow_add: true,
              collapsed: false,
            }
          - label: "Where to Get"
            name: "where_to_get"
            widget: "list"
            required: false
            fields:
              - { label: "Store", name: "store", widget: "string" }
              - {
                  label: "Link",
                  name: "link",
                  widget: "string",
                  pattern: ['^https?:\/\/.*', "Must be a valid URL"],
                }
              - {
                  label: "Date",
                  name: "date",
                  widget: "datetime",
                  date_format: "YYYY-MM-DD",
                  time_format: false,
                }
