backend:
  name: github
  repo: Dimm-ddr/loudlyproud
  branch: preview

media_folder: "static/img/uploads" # Media files will be stored in the repo under static/img/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /img/uploads

collections:

  - name: "books" # Used in routes, e.g., /admin/collections/books
    label: "Books"
    label_singular: "Book"
    folder: "content/books"
    create: true
    slug: "{{fields.slug}}"
    fields:
    - label: "Params"
      name: "params"
      widget: "object"
      fields:
        - {label: "Slug", name: "slug", widget: "string", required: true}
        - {label: "Cover", name: "cover", widget: "image"}
        - {label: "Cover Alt text", name: "coverAlt", widget: "string"}
        - {label: "Tags", name: "tags", widget: "list"}
        - {label: "Authors", name: "authors", widget: "list", required: true}
        - {label: "Translators", name: "translators", widget: "list"}
        - {label: "Languages", name: "languages", widget: "list"}
        - {label: "Page count", name: "page_count", widget: "number"}
        - {label: "Publication Year", name: "publication_year", widget: "datetime"}
        - {label: "Goodreads Link", name: "link", widget: "string"}
        - {label: "Buy Link", name: "buy_link", widget: "list"}
        - {label: "Series", name: "series", widget: "string"}
        - {label: "ISBN", name: "isbn", widget: "string"}
        - {label: "Additional ISBNs", name: "additional_isbns", widget: "list"}
        - {label: "Where to get", name: "where_to_get", widget: "list"}
        - {label: "Russian Edition", name: "russian_translation_status", widget: "select", default: "unknown", options: ["unknown","might_exist","unlikely_to_exist","does_not_exist","exists"]}
        - {label: "Russian Audioversion", name: "russian_audioversion", widget: "boolean", default: false}
        - {label: "Publishers", name: "publishers", widget: "list"}
        - {label: "Description", name: "description", widget: "markdown"}
        - {label: "Short Description", name: "short_description", widget: "markdown"}

site_url: https://loudlyproud.netlify.app/
display_url: https://loudlyproud.netlify.app/