# static/admin/config.yml
local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "books"
    label: "Books"
    folder: "content/ru/books"
    create: true
    fields:
      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          default: false,
          required: true,
        }
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Slug", name: "slug", widget: "string", required: true }
      - { label: "Type", name: "type", widget: "hidden", default: "books" }
      - label: "Params"
        name: "params"
        widget: "object"
        fields:
          - { label: "Book Title", name: "book_title", widget: "string" }
          - {
              label: "Book Description",
              name: "book_description",
              widget: "text",
            }
          - {
              label: "Short Book Description",
              name: "short_book_description",
              widget: "text",
            }
          - { label: "Cover", name: "cover", widget: "string" }
          - { label: "Authors", name: "authors", widget: "list" }
          - { label: "Tags", name: "tags", widget: "list", required: false }
          - {
              label: "Publication Year",
              name: "publication_year",
              widget: "string",
            }
          - { label: "Publishers", name: "publishers", widget: "list" }
          - { label: "Languages", name: "languages", widget: "list" }
          - {
              label: "Russian Translation Status",
              name: "russian_translation_status",
              widget: "select",
              options:
                [
                  "unknown",
                  "might_exist",
                  "unlikely_to_exist",
                  "does_not_exist",
                  "exists",
                ],
            }
          - {
              label: "Russian Audioversion",
              name: "russian_audioversion",
              widget: "boolean",
            }
          - { label: "Cover Alt Text", name: "cover_alt", widget: "string" }
          - { label: "ISBN", name: "isbn", widget: "string" }
          - {
              label: "Additional ISBNs",
              name: "additional_isbns",
              widget: "list",
            }
          - { label: "Page Count", name: "page_count", widget: "string" }
          - {
              label: "Goodreads Link",
              name: "goodreads_link",
              widget: "string",
            }
          - { label: "Buy Link", name: "buy_link", widget: "string" }
          - { label: "Series", name: "series", widget: "string" }
          - { label: "Translators", name: "translators", widget: "list" }
          - label: "Where to Get"
            name: "where_to_get"
            widget: "list"
            fields:
              - { label: "Store", name: "store", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
              - { label: "Date", name: "date", widget: "date" }
