# static/admin/config.yml
local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "books"
    label: "Books"
    folder: "content/ru/books"
    create: true
    fields:
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Type", name: "type", widget: "hidden", default: "books" }
      - label: "Params"
        name: "params"
        widget: "object"
        fields:
          - { label: "Book Title", name: "book_title", widget: "string" }
          - {
              label: "Book Description",
              name: "book_description",
              widget: "text",
            }
          - {
              label: "Short Book Description",
              name: "short_book_description",
              widget: "text",
            }
          - { label: "Cover", name: "cover", widget: "string" }
          - { label: "Authors", name: "authors", widget: "list" }
          - { label: "Tags", name: "tags", widget: "list" }
          - {
              label: "Publication Year",
              name: "publication_year",
              widget: "string",
            }
          - { label: "Publishers", name: "publishers", widget: "list" }
          - { label: "Languages", name: "languages", widget: "list" }
          - {
              label: "Russian Translation Status",
              name: "russian_translation_status",
              widget: "select",
              options: ["exists", "in progress", "unknown"],
            }
          - {
              label: "Russian Audioversion",
              name: "russian_audioversion",
              widget: "select",
              options: ["yes", "no"],
            }
