# static/admin/config.yml
local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

i18n:
  structure: multiple_folders
  locales: [ru, en]
  default_locale: ru

collections:
  - name: books
    label: Books
    folder: "content"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Type", name: "type", widget: "hidden", default: "books"}

