# static/admin/config.yml
local_backend: true

backend:
  name: git-gateway
  branch: preview

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

i18n:
  structure: multiple_folders
  locales: [ru, en]
  default_locale: ru

collections:
  - name: books
    i18n:
      locales: [ru, en]
    label: Books
    label_singular: Book
    folder: "content"
    create: true
    slug: "{{fields.slug}}"
    path: "{{locale}}books/{{fields.slug}}"
    filter: { field: "type", value: "books" }
    identifier_field: "{{fields.title}}"
    fields:
      - { label: "Title", name: "title", widget: "hidden" }
      - { label: "Slug", name: "slug", widget: "hidden" }
      - { label: "Type", name: "type", widget: "hidden", default: "books" }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - label: "Params"
        name: "params"
        widget: "object"
        fields:
          - {
              label: "Book Title",
              name: "bookTitle",
              widget: "string",
              required: true,
            }
          - label: "Book Description"
            name: "book_description"
            widget: "markdown"
            required: false
          - label: "Short Description"
            name: "short_book_description"
            widget: "markdown"
            required: false
          - label: "Cover"
            name: "cover"
            widget: "image"
            required: false
          - label: "Cover Alt text"
            name: "coverAlt"
            widget: "string"
            required: false
          - label: "Tags"
            name: "tags"
            widget: "list"
            required: false
            allow_add: true
            collapsed: false
          - label: "Authors"
            name: "authors"
            widget: "list"
            required: true
            allow_add: true
            collapsed: false
          - label: "Translators"
            name: "translators"
            widget: "list"
            required: false
            allow_add: true
            collapsed: false
          - label: "Languages"
            name: "languages"
            widget: "list"
            required: false
            allow_add: true
            collapsed: false
          - label: "Page count"
            name: "page_count"
            widget: "number"
            required: false
          - label: "First Publication Year"
            name: "publication_year"
            widget: "string"
            required: false
          - label: "ISBN"
            name: "isbn"
            widget: "string"
            required: false
          - label: "Additional ISBNs"
            name: "additional_isbns"
            widget: "list"
            required: false
            allow_add: true
            collapsed: false
          - label: "Series"
            name: "series"
            widget: "string"
            required: false
          - label: "Publishers"
            name: "publishers"
            widget: "list"
            required: false
            allow_add: true
          - label: "Goodreads Link"
            name: "goodreads_link"
            widget: "string"
            required: false
          - label: "Buy Link"
            name: "buy_link"
            widget: "string"
            required: false
            allow_add: true
            collapsed: false
          - label: "Where to Get"
            name: "where_to_get"
            widget: "list"
            required: false
            fields:
              - { label: "Store", name: "store", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
              - { label: "Date", name: "date", widget: "datetime" }
            i18n: true
          - label: "Russian Translation Status"
            name: "russian_translation_status"
            widget: "select"
            default: "unknown"
            options:
              - "unknown"
              - "might_exist"
              - "unlikely_to_exist"
              - "does_not_exist"
              - "exists"
            required: false
          - label: "Russian Audioversion"
            name: "russian_audioversion"
            widget: "select"
            default: "no"
            options:
              - "yes"
              - "no"
            required: false
