# .github/workflows/monitor-tags.yml
name: Monitor New Tags

on:
  pull_request:
    paths:
      - 'content/books/**/*.md'
    types: [opened, synchronize]

jobs:
  check-tags:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
          
      - name: Check for new tags
        run: |
          python .github/scripts/check_new_tags.py
        id: tag-check
      
      - name: Comment on PR
        if: steps.tag-check.outputs.has_new_tags == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const newTags = JSON.parse(fs.readFileSync('new_tags.json', 'utf8'));
            
            let body = '### New Tags Detected\n\n';
            body += 'The following new tags were found in this PR:\n\n';
            
            Object.entries(newTags).forEach(([file, tags]) => {
              body += `**${file}**:\n`;
              tags.forEach(tag => body += `- \`${tag}\`\n`);
            });
            
            body += '\nPlease review these tags and update the tag mapping if necessary.';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
