name: Test Tools

on:
  push:
    paths:
      - '.tools/**'
      - '.github/workflows/test-tools.yml'
      - 'data/tags/**'
  pull_request:
    paths:
      - '.tools/**'
      - '.github/workflows/test-tools.yml'
      - 'data/tags/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .tools/requirements.txt

      - name: Run tests
        run: |
          cd .tools
          PYTHONPATH=$PYTHONPATH:. pytest tags/tests/ --cov=tags --cov-report=xml
